env:
  utopia:  
  - secure: piqhwWnkc6nTuyKSMXIyrb3iAyeVGAMtY4/2B3Zwlb69E6h/KWp7J6CjdF3Qli0xDQb7MdRvXlau+P8MPvgGzQWkq6TqV6jqQ7Za+rM3tGREfvoa2kBiZqjAkVvanIjcw5hwmatDlR3TXn5r4E28Io8MCzLlAXOk2P28wKbhAgwXbaGey5kb50JCmyrSV9EPLbSuDxpHhXwztfluQZkiPcjwn+vmGrzgJbhBYMI+xFeDmE8wjiyYoylXcmhtgCBt4C5BAsi6oLaCapjgW0j4XVauKRl0hYfxxhXpHCWlLQG6aGFyVrQobQVkIsCKp6Kn8r/wA66JPeTu874WcH0Vfo2O2VSP9Z9QdbM/9SnVetbx4bNTz+XxOLSV7JmsS3Vzp6cdejDKehS3cXsdkI2uolEMXlixcIdP2Mjnf7cwD1v6FyOAuTwwcTUIt7lqHtB7RNNCCt0doitgdByxGraLuxD69RjgCfjRs2QjbDJ5vSZCO/IAJ3vNXH/Otus4TojcVtj0RZQUqApM79DEXwM8sBQNJnpf7iLYk3sA3gQzTM1hYbdqrZBDqET2Uv9iTV3gzJghpSyDuWYDFAU3YFZ744VGQcJQidcySQ9YgOTMZjp4GOtUdMWEMYN1TzkqeQz0MK50E0RWDA1vBiYYmpQBOuPffZF47lgdmDgsh/umbP0=
language: node_js
node_js:
- '11'
# services:
# - docker
jobs:
  include:
  - stage: Installing dependencies
    script: yarn install
  - stage: Unit test
    script: yarn test:prod
  # - stage: Docker
  #   script:
  #     - docker build -f Dockerfile-prod -t utopia .
  #     - docker run -it -p 80:80 --rm utopia
  - stage: Deploy
    if: branch = master
    script: 
      - npm install -g firebase-tools
      - yarn build
      - firebase deploy --token $utopia
# fixed
