env:
  global:
    secure: VI6nJRoA1wTDgXJh0dbDpHbp6w8fa/vvVZHvLCPQLSvw25FRbtwI7iU4vS5cUFm24DELrpSebSsSTQbFEe4N1n/cbuGXxLxcwgwETnWI8yHBqa2I6zmt1wTT9ppp2SEmtUuMgrUHHQsMSioOKAntA74xWi6WOqUa5oVw+PScIu0x7VYwnqmKswDLVM5OXYzPwGwUmx5rUtlvcQEFadmsAQts+Q8ELlZ9IGSRvSPV4whG66HOoA3NlueXZP4Csps9YciYX4nlHKPbeHuq7460PqbJbLj4l2TDWFDNNR2+7VSTsG0BSYP6q88cUUY54+lM0V/2PtSTFnrki8ulsg6zcEXqODiJJe1AzFRHa4wxYJKoZLXZarsmMI+yU9dGuyaUZYFHvNEeoUGyP8SKc/MQVl/Nsk06vR10GcdjkxDKxJ7MxmGU/H7TLBfleLbxB1g43bmoph1v3/4RgnB3MvFYZodvoJzmO2Fb/xvjaO3QMr5BIRMtbGrsnhK172iZeMoQrfCVDV+G1aHGpsEUoaaqdmVq/+9+LsYDgx3IYPSZ3o8k3JsFwR2D8GtyjwbPXWliEoBhrzAVDH1VISUyMl3mUCnyk7DzlrZYmdDMPOXFU1PqT2YnazQUU7ofam27vuS78rc9/vmxb/UdbbbkE+6PwOzyws2VUBYlZA3du7V9RY8=

language: node_js
node_js:
- '10'
services:
- docker

jobs:
  include:
    - stage: Installing dependencies
      script: yarn install
    - stage: Unit test
      script: yarn test:prod
    - stage: Deploy
      deploy: 
        provider: firebase
        token:
          secure: "utopia"
        message: "echo 'Ready'"

# - docker build -f Dockerfile-prod -t utopia .
# - docker run -it -p 80:80 --rm utopia